name: yolo-alarm
options:
  bundleIdPrefix: com.yoloalarm
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

schemes:
  yolo-alarm:
    build:
      targets:
        yolo-alarm: all
        yolo-alarm-widgets: all
    run:
      executable: yolo-alarm
    profile:
      executable: yolo-alarm
    archive:
      executable: yolo-alarm

settings:
  base:
    DEVELOPMENT_TEAM: 86CCQ2AT2P
    MARKETING_VERSION: "1.0.2"
    CURRENT_PROJECT_VERSION: "1"

targets:
  yolo-alarm:
    type: application
    platform: iOS
    sources:
      - path: yolo-alarm
        excludes:
          - "**/*.md"
    resources:
      - path: yolo-alarm/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yoloalarm.app
        INFOPLIST_FILE: yolo-alarm/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_LIVE_ACTIVITIES: YES
        ENABLE_PREVIEWS: YES
    info:
      path: yolo-alarm/Info.plist
      properties:
        CFBundleDisplayName: yolo alarm
        CFBundleName: yolo-alarm
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIBackgroundModes:
          - audio
        NSMicrophoneUsageDescription: "yolo alarm needs microphone access to detect when you start moving around during your wake window."
        NSSupportsLiveActivities: true
        ITSAppUsesNonExemptEncryption: false
    entitlements:
      path: yolo-alarm/yolo-alarm.entitlements
      properties:
        com.apple.security.app-sandbox: true
    dependencies:
      - target: yolo-alarm-widgets

  yolo-alarm-widgets:
    type: app-extension
    platform: iOS
    sources:
      - path: yolo-alarm-widgets
      - path: yolo-alarm/Models/YOLOActivityAttributes.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yoloalarm.app.widgets
        INFOPLIST_FILE: yolo-alarm-widgets/Info.plist
        SKIP_INSTALL: YES
        CODE_SIGN_STYLE: Automatic
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    info:
      path: yolo-alarm-widgets/Info.plist
      properties:
        CFBundleDisplayName: yolo-alarm-widgets
        CFBundleName: yolo-alarm-widgets
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
