name: YOLO
options:
  bundleIdPrefix: com.yoloalarm
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

schemes:
  YOLO:
    build:
      targets:
        YOLO: all
        YOLOWidgets: all
    run:
      executable: YOLO
    profile:
      executable: YOLO
    archive:
      executable: YOLO

settings:
  base:
    DEVELOPMENT_TEAM: 86CCQ2AT2P
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

targets:
  YOLO:
    type: application
    platform: iOS
    sources:
      - path: YOLO
        excludes:
          - "**/*.md"
    resources:
      - path: YOLO/Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yoloalarm.app
        INFOPLIST_FILE: YOLO/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_LIVE_ACTIVITIES: YES
        ENABLE_PREVIEWS: YES
    info:
      path: YOLO/Info.plist
      properties:
        CFBundleDisplayName: yolo alarm
        CFBundleName: yolo-alarm
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIBackgroundModes:
          - audio
          - processing
        NSMicrophoneUsageDescription: "YOLO needs microphone access to detect when you start moving around during your wake window."
        NSSupportsLiveActivities: true
    entitlements:
      path: YOLO/YOLO.entitlements
      properties:
        com.apple.security.app-sandbox: true
    dependencies:
      - target: YOLOWidgets

  YOLOWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: YOLOWidgets
      - path: YOLO/Models/YOLOActivityAttributes.swift
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yoloalarm.app.widgets
        INFOPLIST_FILE: YOLOWidgets/Info.plist
        SKIP_INSTALL: YES
        CODE_SIGN_STYLE: Automatic
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"
    info:
      path: YOLOWidgets/Info.plist
      properties:
        CFBundleDisplayName: YOLOWidgets
        CFBundleName: YOLOWidgets
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
